# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.7
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.





from sys import version_info
if version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_CPPFFT', [dirname(__file__)])
        except ImportError:
            import _CPPFFT
            return _CPPFFT
        if fp is not None:
            try:
                _mod = imp.load_module('_CPPFFT', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _CPPFFT = swig_import_helper()
    del swig_import_helper
else:
    import _CPPFFT
del version_info
try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.


def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr_nondynamic(self, class_type, name, static=1):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    if (not static):
        return object.__getattr__(self, name)
    else:
        raise AttributeError(name)

def _swig_getattr(self, class_type, name):
    return _swig_getattr_nondynamic(self, class_type, name, 0)


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object:
        pass
    _newclass = 0


class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _CPPFFT.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _CPPFFT.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _CPPFFT.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _CPPFFT.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _CPPFFT.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _CPPFFT.SwigPyIterator_equal(self, x)

    def copy(self):
        return _CPPFFT.SwigPyIterator_copy(self)

    def next(self):
        return _CPPFFT.SwigPyIterator_next(self)

    def __next__(self):
        return _CPPFFT.SwigPyIterator___next__(self)

    def previous(self):
        return _CPPFFT.SwigPyIterator_previous(self)

    def advance(self, n):
        return _CPPFFT.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _CPPFFT.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _CPPFFT.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _CPPFFT.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _CPPFFT.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _CPPFFT.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _CPPFFT.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _CPPFFT.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

class vectorf(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectorf, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectorf, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _CPPFFT.vectorf_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _CPPFFT.vectorf___nonzero__(self)

    def __bool__(self):
        return _CPPFFT.vectorf___bool__(self)

    def __len__(self):
        return _CPPFFT.vectorf___len__(self)

    def pop(self):
        return _CPPFFT.vectorf_pop(self)

    def __getslice__(self, i, j):
        return _CPPFFT.vectorf___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _CPPFFT.vectorf___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _CPPFFT.vectorf___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _CPPFFT.vectorf___delitem__(self, *args)

    def __getitem__(self, *args):
        return _CPPFFT.vectorf___getitem__(self, *args)

    def __setitem__(self, *args):
        return _CPPFFT.vectorf___setitem__(self, *args)

    def append(self, x):
        return _CPPFFT.vectorf_append(self, x)

    def empty(self):
        return _CPPFFT.vectorf_empty(self)

    def size(self):
        return _CPPFFT.vectorf_size(self)

    def clear(self):
        return _CPPFFT.vectorf_clear(self)

    def swap(self, v):
        return _CPPFFT.vectorf_swap(self, v)

    def get_allocator(self):
        return _CPPFFT.vectorf_get_allocator(self)

    def begin(self):
        return _CPPFFT.vectorf_begin(self)

    def end(self):
        return _CPPFFT.vectorf_end(self)

    def rbegin(self):
        return _CPPFFT.vectorf_rbegin(self)

    def rend(self):
        return _CPPFFT.vectorf_rend(self)

    def pop_back(self):
        return _CPPFFT.vectorf_pop_back(self)

    def erase(self, *args):
        return _CPPFFT.vectorf_erase(self, *args)

    def __init__(self, *args):
        this = _CPPFFT.new_vectorf(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def push_back(self, x):
        return _CPPFFT.vectorf_push_back(self, x)

    def front(self):
        return _CPPFFT.vectorf_front(self)

    def back(self):
        return _CPPFFT.vectorf_back(self)

    def assign(self, n, x):
        return _CPPFFT.vectorf_assign(self, n, x)

    def resize(self, *args):
        return _CPPFFT.vectorf_resize(self, *args)

    def insert(self, *args):
        return _CPPFFT.vectorf_insert(self, *args)

    def reserve(self, n):
        return _CPPFFT.vectorf_reserve(self, n)

    def capacity(self):
        return _CPPFFT.vectorf_capacity(self)
    __swig_destroy__ = _CPPFFT.delete_vectorf
    __del__ = lambda self: None
vectorf_swigregister = _CPPFFT.vectorf_swigregister
vectorf_swigregister(vectorf)

class vectorc(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, vectorc, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, vectorc, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _CPPFFT.vectorc_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _CPPFFT.vectorc___nonzero__(self)

    def __bool__(self):
        return _CPPFFT.vectorc___bool__(self)

    def __len__(self):
        return _CPPFFT.vectorc___len__(self)

    def pop(self):
        return _CPPFFT.vectorc_pop(self)

    def __getslice__(self, i, j):
        return _CPPFFT.vectorc___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _CPPFFT.vectorc___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _CPPFFT.vectorc___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _CPPFFT.vectorc___delitem__(self, *args)

    def __getitem__(self, *args):
        return _CPPFFT.vectorc___getitem__(self, *args)

    def __setitem__(self, *args):
        return _CPPFFT.vectorc___setitem__(self, *args)

    def append(self, x):
        return _CPPFFT.vectorc_append(self, x)

    def empty(self):
        return _CPPFFT.vectorc_empty(self)

    def size(self):
        return _CPPFFT.vectorc_size(self)

    def clear(self):
        return _CPPFFT.vectorc_clear(self)

    def swap(self, v):
        return _CPPFFT.vectorc_swap(self, v)

    def get_allocator(self):
        return _CPPFFT.vectorc_get_allocator(self)

    def begin(self):
        return _CPPFFT.vectorc_begin(self)

    def end(self):
        return _CPPFFT.vectorc_end(self)

    def rbegin(self):
        return _CPPFFT.vectorc_rbegin(self)

    def rend(self):
        return _CPPFFT.vectorc_rend(self)

    def pop_back(self):
        return _CPPFFT.vectorc_pop_back(self)

    def erase(self, *args):
        return _CPPFFT.vectorc_erase(self, *args)

    def __init__(self, *args):
        this = _CPPFFT.new_vectorc(*args)
        try:
            self.this.append(this)
        except:
            self.this = this

    def push_back(self, x):
        return _CPPFFT.vectorc_push_back(self, x)

    def front(self):
        return _CPPFFT.vectorc_front(self)

    def back(self):
        return _CPPFFT.vectorc_back(self)

    def assign(self, n, x):
        return _CPPFFT.vectorc_assign(self, n, x)

    def resize(self, *args):
        return _CPPFFT.vectorc_resize(self, *args)

    def insert(self, *args):
        return _CPPFFT.vectorc_insert(self, *args)

    def reserve(self, n):
        return _CPPFFT.vectorc_reserve(self, n)

    def capacity(self):
        return _CPPFFT.vectorc_capacity(self)
    __swig_destroy__ = _CPPFFT.delete_vectorc
    __del__ = lambda self: None
vectorc_swigregister = _CPPFFT.vectorc_swigregister
vectorc_swigregister(vectorc)

class FastFourierTransform(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, FastFourierTransform, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, FastFourierTransform, name)
    __repr__ = _swig_repr

    def hanning(self, data):
        return _CPPFFT.FastFourierTransform_hanning(self, data)

    def transform(self, data, window=True):
        return _CPPFFT.FastFourierTransform_transform(self, data, window)

    def center_on_octaves(self, data, bandwidth):
        return _CPPFFT.FastFourierTransform_center_on_octaves(self, data, bandwidth)

    def inverse_transform(self, data):
        return _CPPFFT.FastFourierTransform_inverse_transform(self, data)

    def float_transform(self, data, window=True):
        return _CPPFFT.FastFourierTransform_float_transform(self, data, window)

    def to_merge_calculation(self, stage, out):
        return _CPPFFT.FastFourierTransform_to_merge_calculation(self, stage, out)

    def reverse_bit_sort(self, data):
        return _CPPFFT.FastFourierTransform_reverse_bit_sort(self, data)

    def __init__(self, length, exponent):
        this = _CPPFFT.new_FastFourierTransform(length, exponent)
        try:
            self.this.append(this)
        except:
            self.this = this
    __swig_destroy__ = _CPPFFT.delete_FastFourierTransform
    __del__ = lambda self: None
FastFourierTransform_swigregister = _CPPFFT.FastFourierTransform_swigregister
FastFourierTransform_swigregister(FastFourierTransform)

# This file is compatible with both classic and new-style classes.


